//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_DataGridView.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_2
    {
        public int 序 { get; set; }
        public Nullable<int> 货号 { get; set; }
        public Nullable<int> 条码 { get; set; }
        public string 品名规格 { get; set; }
        public Nullable<int> 数量 { get; set; }
        public Nullable<int> 单价 { get; set; }
        public Nullable<int> 金额 { get; set; }
    }
}
