//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_DataGridView.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestAccount
    {
        public int ID { get; set; }
        public string userName { get; set; }
        public string passWord { get; set; }
    }
}
